name: Publish

on: 
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Pypi credentials
      run: |  
        poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}

    - name: Package
      run: poetry publish